### ISSUE TITLE
Latest version of enscons fails to install using python 2

### ISSUE THREAD

**Issue by pxul** [dholth/enscons#10]
```
$ ./venv/bin/pip install enscons
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting enscons
  Using cached enscons-0.24.2-py2.py3-none-any.whl (24 kB)
Collecting packaging
  Using cached packaging-20.8-py2.py3-none-any.whl (39 kB)
Collecting scons>=3.0.5
  Using cached scons-3.1.2-py2.py3-none-any.whl (837 kB)
Collecting attrs
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
ERROR: Could not find a version that satisfies the requirement editables (from enscons) (from versions: none)
ERROR: No matching distribution found for editables (from enscons)
```

This occurs with all versions of `0.24` (`0.24.0` to `0.24.2`), but not with `0.23.0`.

I'm aware I should have stopped using python 2 long ago, and we are in the process of moving across to python 3 however this latest build of enscons means we are unable to install cryptacular as the most recent version of ensons is installed by default when installing.

Was the removal of versions for python 2 intentional? I couldn't see anything in the documentation (or on the pypi page) about it.

**Comment by dholth** [comment]
Glad to hear you're interested in `enscons`. I'm working on PEP517-style editable installation but did not realize that package would cause this issue.

It will need to be made a conditional dependency. `editables;python_version>"3.0"` with a conditional import.

**Comment by pxul** [comment]
Hi, thanks very much for the response. This issue arose from trying to install `cryptacular` in python 2, which declares `enscons` as a requirement:
```console
$ cat pyproject.toml
[build-system]
requires = ["pytoml>=0.1", "enscons>=0.22"]
build-backend = "enscons.api"
...
...
```
and results in the error in my previous comment. For the time being we are vendoring our own copy of `cryptacular` to address the issue, but if this could be fixed it would be much appreciated.

**Comment by pxul** [comment]
Many thanks, @dholth this issue has been addressed with your latest release.
