### ISSUE TITLE
Build errors when "sdist" is not a default target

### ISSUE THREAD

**Issue by magv** [dholth/enscons#12]
Hi, Daniel. I'm trying to use escons, and I've run into a problem: if `sdist` is not added as a default target, then the recommended way of building packages, `python3 -m build`, fails with this fairly cryptic message:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../site-packages/build/__init__.py", line 311, in _call_backend
    raise BuildBackendException(exception)
build.BuildBackendException: Backend operation failed: TypeError("join() argument must be str or bytes, not 'NoneType'",)

ERROR Backend operation failed: TypeError("join() argument must be str or bytes, not 'NoneType'",)
```

The problem is that in [build_sdist()](/dholth/enscons/blob/ca4fcaade29331e570c965c2bb7f7e222e81ac9e/enscons/api.py#L43) the filename of the sdist tarball is obtained by enumerating `SCons.Script.DEFAULT_TARGETS`, and looking for the first one that ends with `.tar.gz`. This means that if `sdist` is not a default target, this logic fails. Also, if there are other `.tar.gz` files being built, this can fail too.

Can this logic be modified somehow so that I could remove `sdist` from default targets and leave it just as an alias? I'd like to have other actions to be performed by default; building packages is a rare thing to do after all.

**Comment by dholth** [comment]
Yes, the default targets logic is hacky. If we can figure out a better way to inspect scons I'm for it

**Comment by magv** [comment]
What about reusing the same trick that "bdist_wheel" is using?
Something like this:
```diff
diff --git a/enscons/__init__.py b/enscons/__init__.py
index a702913..e0db400 100644
--- a/enscons/__init__.py
+++ b/enscons/__init__.py
@@ -566,6 +566,7 @@ def SDist(env, target=None, source=None):
         TARGID=0,
         TARMTIME=SOURCE_EPOCH_TGZ,
     )
+    env.Alias("sdist", sdist)
     return sdist
 
 
diff --git a/enscons/api.py b/enscons/api.py
index bbf582d..cc67451 100644
--- a/enscons/api.py
+++ b/enscons/api.py
@@ -42,14 +42,7 @@ def build_wheel(wheel_directory, settings, metadata_directory=None):
 
 def build_sdist(sdist_directory, settings):
     sys.argv[1:] = ["--dist-dir=" + sdist_directory, "sdist"]
-    try:
-        SCons.Script.Main.main()
-    except SystemExit as e:
-        pass
-    for target in SCons.Script.DEFAULT_TARGETS:
-        target_name = str(target)
-        if target_name.endswith(".tar.gz"):
-            return os.path.basename(target_name)
+    return _run("sdist")
 
 
 # experimental PEP517-style editable installation
```

**Comment by dholth** [comment]
Looks like a good idea. I don't know why I didn't do it that way in the first place.
