### ISSUE TITLE
Is setup.py still necessary?

### ISSUE THREAD

**Issue by oczkoisse** [dholth/enscons#22]
I've been trying out enscons in a personal project that needs custom build steps and so far, I like it a lot! Thanks for working on this!

I noticed that all provided example projects except [nonstdlib](https://github.com/dholth/nonstdlib/) seem to keep a `setup.py` file. This is consistent with advice in [README](https://github.com/dholth/enscons/blob/master/README.rst):

> If you are not starting from an existing `setup.py`, get enscons' source code, and copy `pyproject.toml`, `SConstruct`, and `setup.py` into your own project.

It seems that both `pip install .` and `python -m SCons --enable-virtualenv` seem to work without needing `setup.py`. However, editable install via `pip install -e .` only works with `setup.py`.

Besides editable installs, is there any other reason to keep `setup.py` in project root? If not, maybe the instructions in README could be changed?

**Comment by dholth** [comment]
I'm delighted to hear that you're enjoying it.

We finished [PEP 660](https://www.python.org/dev/peps/pep-0660/), and I released an updated version of enscons that uses it. It will allow "pip install -e" to work without a setup.py. Let us know if this pip branch works as intended. https://github.com/pypa/pip/pull/8212

**Comment by oczkoisse** [comment]
I just did an editable install of my project using pip from pypa/pip#8212 and it worked without any problems whatsoever. I had deleted `setup.py` beforehand. Like any editable install, changes in my source tree propagated to the installed project just fine. Uninstallation was clean and without errors too. I tested it twice to be sure :). Please let me know if you need me to test anything else.

This is really great! Thanks for updating `enscons` for PEP 660. I hope we can see a pip release that merges these changes soon.
