### ISSUE TITLE
Perform build steps for editable install

### ISSUE THREAD

**Issue by oczkoisse** [dholth/enscons#23]
As part of build, I invoke an external tool to convert certain files to Python scripts. The build script works fine for installation from source directory, in that the created wheels and source distributions contain the auto-generated Python files. However, for editable installation, I think `SConstruct` file doesn't run at all. Moreover, configured `tool.enscons.entry_points` don't get installed as executables. Is this expected behavior?

I'm using `enscons` 0.26 in case it matters.

**Comment by dholth** [comment]
It builds a target called `editable` https://github.com/dholth/enscons/blob/master/enscons/api.py#L48 defined at https://github.com/dholth/enscons/blob/master/enscons/__init__.py#L486

It should build those other things, but it's possible something was missed.

**Comment by ShadowJonathan** [comment]
This seems to work, but this function hasnt been defined: https://peps.python.org/pep-0660/#prepare-metadata-for-build-editable

**Comment by dholth** [comment]
We can see it's optional, at the end of that section "If a build frontend needs this information and the method is not defined, it should call build_editable and look at the resulting metadata directly." Our `build_editable` should be faster than doing something extra for `build_metadata`.

**Comment by ShadowJonathan** [comment]
Odd, `pip` seems to not find it optional, unless my install was funky for a second

**Comment by dholth** [comment]
I had to update enscons for Python 3.12, and then something like pip install --no-build-isolation -e . works in the enscons checkout.
