### ISSUE TITLE
Support for ./src/packagename/file.py trees?

### ISSUE THREAD

**Issue by swork** [dholth/enscons#29]
Whl() and SDist() run in top-level SConstruct seem to reflect source item path components into the build products, so a src-style tree results in wheels with zip members like src/modulename/file.py (implies "import src/modulename" instead of expected "import modulename"). All of the examples I found use flat source trees. Is there support for building a wheel containing "modulename/file.py" from a source tree that puts python source files under ./src/modulename? How do I invoke that support? Thanks.

**Comment by dholth** [comment]
IIRC try passing `root='src'` to this call https://github.com/dholth/enscons/blob/master/SConstruct#L41
