### ISSUE TITLE
How to add LICENSE file to dist-info

### ISSUE THREAD

**Issue by cwiede** [dholth/enscons#38]
The setuptools add existing LICENSE files to the dist-info data (in addition to eventually available license="MIT" arguments given in the setup() function). 

Is this actually possible with enscons? It seems that LICENSE files are only added to source distributions, but not to wheels.

Maybe it would be nice to have an option to add files to the dist-info directory by adding a new builtin category "dist-info"?

At the moment I'm using this

```python
lib = env.Whl(target, package_source, root=".")
lib += env.InstallAs(env["DIST_INFO_PATH"].File("LICENSE"), ["LICENSE"])
whl = env.WhlFile(lib)
```

which seems to work, but I'm not sure whether this is actually the right way to do it?

**Comment by dholth** [comment]
Yes, that's a fine way to do it.
