### ISSUE TITLE
Issues raised by SCons siletnly ignored, resulting in garbage wheels

### ISSUE THREAD

**Issue by MKuranowski** [dholth/enscons#40]
I'm trying to do recreate something along the lines of [hello-pyrust](https://github.com/dholth/hello-pyrust/) but with Zig.
`zig` fails for its reasons, however enscons jsut slicenses the error and pretends like nothing has happened, resulting in completely unusable wheels.

```terminal
$ python -m build
...
* Building wheel...
...
os.chdir('./zigpkg')
zig build -Doptimize=ReleaseSafe
error: AppDataDirUnavailable
os.chdir('/tmp/build-via-sdist-uw4njyqz/pypkg-1.0.0')
scons: *** [zigpkg/zig-out/lib] Error 1
scons: building terminated because of errors.
Successfully built pypkg-1.0.0.tar.gz and pypkg-1.0.0-cp311-cp311-linux_x86_64.whl
```

If scons has terminated because of errors, how could the build be successful?

---

https://github.com/dholth/enscons/blob/417717053e4ac988dc3c6bd8782978152e6826f1/enscons/api.py#L24C5-L27C13

Looks extremely fishy, at the very least the except body should be `catch SystemExit as e: raise RuntimeError("scons failed") from e`

**Comment by mwichmann** [comment]
At least it seems prudent to check the exit status of SCons. Since scons is run in-process, you don't want enscons to quit when SCons finishes - unless SCons is reporting a failure. So maybe toss in an `if e.code:`?

**Comment by dholth** [comment]
Fixed in https://github.com/dholth/enscons/pull/44/commits/98030cb402b6f2bfeb420efcdad9331a7b0932ea
